### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bluesaka111** [VeltTechnologies/graphene-desktop#12]
Support click on mouse pad.
Main menu "Start menu" item alignment set to left with padding. Center align looks... ugly and weird.
Expand Windows manager start menu and add some useful section like "Frequently visit place" "Recent files" "System Features" etc...

Few lightweight gadgets for Windows Manager is also helpful.

**Comment by azsn** [comment]
Graphene has been updated significantly since the last ISO release, and now has left-aligned text in the Launcher menu.

The other features you mentioned will probably come eventually, but the more basic stuff comes first. Also, VeltOS is developed through the voting platform at [velt.io/community](www.velt.io/community), so post feature ideas there. (Although currently I haven't been reading much of what's posted there, since I'm attempting to get all the basic stuff done first.)
