### ISSUE TITLE
Application menu does not update to show newly installed applications

### ISSUE THREAD

**Issue by Secris** [VeltTechnologies/graphene-desktop#2]
When you install a program the menu should update to allow you to launch the application

**Comment by Secris** [comment]
It seems the menu is able to detect some applications and update accordingly.
Examples:
deadbeef - detected and displayed
gnome-builder - detected and displayed
syncthing-gtk - did not detect had to log out and back in

**Comment by azsn** [comment]
Graphene uses GNOME's .desktop listing API to find applications. If an application doesn't show up after installing, it's probably because the application's install script doesn't add the .desktop file correctly or something.
This may be fixed in the new version of Graphene, since the method of listing apps has been changed slightly, however I was unable to install syncthing-gtk with pacman to test it (missing dependencies).
